# Generated by Django 4.2.20 on 2025-03-20 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_servicecompany_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.servicecompany', verbose_name='Организация, проводившая ТО'),
        ),
    ]
