# Generated by Django 4.2.20 on 2025-03-20 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_maintenance_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='organization',
            field=models.CharField(choices=[('Самостоятельно', 'Самостоятельно'), ('ООО Промышленная техника', 'ООО Промышленная техника'), ('ООО Силант', 'ООО Силант'), ('ООО ФНС', 'ООО ФНС')], default='Самостоятельно', max_length=255, verbose_name='Организация, проводившая ТО'),
        ),
    ]
