# Generated by Django 4.2.20 on 2025-04-15 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_maintenance_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.servicecompany', verbose_name='Организация, проводившая ТО'),
        ),
    ]
