# Generated by Django 4.2.20 on 2025-04-17 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_maintenance_organization'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicecompany',
            options={'verbose_name': 'Сервисная компания', 'verbose_name_plural': 'Сервисные компании'},
        ),
        migrations.AlterField(
            model_name='machine',
            name='contract_info',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Договор поставки №, дата'),
        ),
    ]
